### ISSUE TITLE
Automated Pack Migration

### ISSUE THREAD

**Issue by capSAR273** [RundownRhino/OmnifactoryGuides#15]
When updating the dev version of the pack, various folders and files need to be moved over to keep things intact. I wrote a short Powershell script to bring the recommended files over automatically to save time. It prompts the user for the old pack's minecraft folder path, and the new path. Saves, waypoints, and some other files outlined in [Playing On Dev](https://github.com/OmnifactoryDevs/OmnifactoryGuides/blob/latest/guides/PlayingOnDev.md) are moved to where they need to be.

I have tested this for my own use for a few versions and it works well so far. I've linked to the latest version of the script, there shouldn't need to be any other changes but in case there are I will update it.

**[Script Here](https://github.com/capSAR273/omnifactory-migrator)**

**Comment by Exaxxion** [comment]
Moved the issue over to our guides repo. Thanks for taking the time to make this utility. Feel free to submit a pull request linking to it in the Playing On Dev guide.

**Comment by capSAR273** [comment]
#16 Should be all set now!
